sudo: false

before_install:
 - chmod +x gradlew
 - chmod +x src/test/resources/browsermob-proxy-2.1.2/bin/browsermob-proxy
 - src/test/resources/browsermob-proxy-2.1.2/bin/browsermob-proxy -port 8080 -address 127.0.0.1

language: java
jdk:
  - oraclejdk8

cache:
    directories:
    - $HOME/.m2

script:
    - ./gradlew test --debug